import { useEffect, useState } from 'react';
import { Link, Navigate, Outlet, Route, Routes, useLocation, useNavigate } from 'react-router-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { Alert, App as AntApp, Avatar, Badge, Button, Card, Drawer, Dropdown, Form, Input, Layout, Menu, Result, Space, Spin, Tag, Tooltip } from 'antd';
import { AppstoreOutlined, BarChartOutlined, CalendarOutlined, CoffeeOutlined, CustomerServiceOutlined, DashboardOutlined, DatabaseOutlined, DesktopOutlined, DollarOutlined, LockOutlined, LogoutOutlined, MenuOutlined, ReloadOutlined, SafetyCertificateOutlined, ShopOutlined, TeamOutlined, UserOutlined } from '@ant-design/icons';
import { api, apiMode, readSession, writeSession } from './api';
import { homeFor, roleLabel, type Role, type Session, type Workspace } from './domain';
import { modules } from './modules';
import { ErrorState } from './components';
import { ResourcePage } from './ResourcePage';
import { DashboardPage } from './DashboardPage';
import { MachinesPage } from './MachinesPage';
import { ReportsPage } from './ReportsPage';
import { StaffPage } from './StaffPage';
import { connectRealtime } from './realtime';

function Login({ session }: { session: Session|null }) {
  const navigate=useNavigate(),[form]=Form.useForm(); const [busy,setBusy]=useState(false),[error,setError]=useState('');
  if(session)return <Navigate replace to={homeFor(session.user.role)}/>;
  async function login(values:{username:string;password:string}) {
    setBusy(true);setError('');try {const result=await api<Session>('/auth/login','POST',values);if(result.user.role==='Customer'){setError('Tài khoản khách sử dụng ứng dụng desktop InternetCafe Client.');return;}writeSession(result);navigate(homeFor(result.user.role),{replace:true});}catch(e){setError((e as Error).message);}finally{setBusy(false);}
  }
  return <main className="login-page"><section className="login-story"><Link className="brand" to="/login"><span className="brand-mark"><DesktopOutlined/></span><span>Internet<span className="brand-accent">Cafe</span><small>QUẢN LÝ THÔNG MINH</small></span></Link><div className="story-content"><div className="story-pill"><span/> MỘT KHÔNG GIAN. MỌI HOẠT ĐỘNG.</div><h1>Vận hành gọn gàng.<br/>Khách chơi an tâm.</h1><p>Phòng máy, dịch vụ và đội ngũ của bạn — kết nối trong một nơi làm việc rõ ràng.</p><div className="story-grid">{[[<DesktopOutlined/>,'Phòng máy','Theo dõi phiên chơi'],[<CoffeeOutlined/>,'Dịch vụ','Tiếp nhận đơn F&B'],[<TeamOutlined/>,'Đội ngũ','Lịch làm & chấm công']].map(([icon,title,desc],i)=><div key={i}>{icon}<strong>{title}</strong><small>{desc}</small></div>)}</div></div><p className="story-footer">Dành cho một quán InternetCafe · Phiên bản frontend demo</p></section><section className="login-panel"><div className="login-form"><Tag bordered={false} color="cyan">KHÔNG GIAN LÀM VIỆC</Tag><h2>Chào mừng trở lại</h2><p className="muted">Đăng nhập để bắt đầu ca làm của bạn.</p>{error&&<Alert type="error" showIcon title={error} className="section-alert"/>}<Form form={form} layout="vertical" onFinish={login} initialValues={{username:'manager',password:'Demo@123'}}><Form.Item name="username" label="Tên đăng nhập" rules={[{required:true,message:'Nhập tên đăng nhập.'}]}><Input prefix={<UserOutlined/>} autoComplete="username" size="large"/></Form.Item><Form.Item name="password" label="Mật khẩu" rules={[{required:true,message:'Nhập mật khẩu.'}]}><Input.Password prefix={<LockOutlined/>} autoComplete="current-password" size="large"/></Form.Item><Button type="primary" htmlType="submit" size="large" block loading={busy}>Đăng nhập</Button></Form><div className="demo-logins"><div className="eyebrow">THỬ NHANH THEO VAI TRÒ</div><Space wrap>{(['manager','cashier','staff','admin','owner'] as const).map(username=><Button key={username} size="small" onClick={()=>{form.setFieldsValue({username,password:'Demo@123'});setError('');}}>{({manager:'Quản lý',cashier:'Thu ngân',staff:'Nhân viên',admin:'Admin',owner:'Chủ quán'})[username]}</Button>)}</Space><p>Mật khẩu demo: <code>Demo@123</code>. Dữ liệu mô phỏng, chưa kết nối backend sản xuất.</p></div><div className="login-security"><SafetyCertificateOutlined/> Quyền truy cập được kiểm tra theo từng nghiệp vụ.</div></div></section></main>;
}
const iconFor: Record<string,React.ReactNode>={ 'Vận hành':<DesktopOutlined/>, 'Thực đơn & kho':<CoffeeOutlined/>, 'Khách hàng & CRM':<CustomerServiceOutlined/>, 'Nhân sự':<TeamOutlined/>, 'Quản trị hệ thống':<SafetyCertificateOutlined/> };
function Shell({session}:{session:Session}) {
  const location=useLocation(),navigate=useNavigate(),queryClient=useQueryClient();const [mobile,setMobile]=useState(false),[online,setOnline]=useState(navigator.onLine);const {modal}=AntApp.useApp();
  const query=useQuery({queryKey:['workspace',session.accessToken],queryFn:()=>api<Workspace>('/workspace'),refetchInterval:5000});
  const refresh=async()=>{await query.refetch();};
  useEffect(()=>{const change=()=>setOnline(navigator.onLine);window.addEventListener('online',change);window.addEventListener('offline',change);return()=>{window.removeEventListener('online',change);window.removeEventListener('offline',change);};},[]);
  useEffect(()=>connectRealtime(session.accessToken,()=>{void queryClient.invalidateQueries({queryKey:['workspace']});}),[session.accessToken,queryClient]);
  const role=session.user.role,isAdmin=role==='Admin',isStaff=role==='Staff';
  const items = isAdmin ? [{key:'/system/accounts',icon:<SafetyCertificateOutlined/>,label:'Tài khoản & phân quyền'},{key:'/system/permissions',icon:<LockOutlined/>,label:'Ma trận quyền'},{key:'/system/products',icon:<CoffeeOutlined/>,label:'Tra cứu sản phẩm'},{key:'/system/suppliers',icon:<ShopOutlined/>,label:'Tra cứu nhà cung cấp'}] : isStaff ? [{key:'/staff/home',icon:<UserOutlined/>,label:'Không gian cá nhân'}] : [
    {key:'/management/overview',icon:<DashboardOutlined/>,label:'Tổng quan'}, {key:'/management/computers',icon:<DesktopOutlined/>,label:'Phòng máy'},
    ...[...new Set(modules.filter(m=>m.roles.includes(role)).map(m=>m.section))].map(section=>({type:'group' as const,label:section,children:modules.filter(m=>m.section===section&&m.roles.includes(role)).map(m=>({key:`/management/${m.key}`,icon:iconFor[section],label:m.title}))})),
    ...(['Owner','Manager'].includes(role)?[{key:'/management/reports',icon:<BarChartOutlined/>,label:'Báo cáo & thống kê'}]:[]),
  ];
  function logout(){modal.confirm({title:'Đăng xuất khỏi InternetCafe?',content:'Các thay đổi chưa lưu trong biểu mẫu sẽ mất.',okText:'Đăng xuất',cancelText:'Ở lại',onOk:()=>{writeSession(null);queryClient.clear();navigate('/login',{replace:true});}});}
  const nav=<><Link className="brand" to={homeFor(role)}><span className="brand-mark">{isAdmin?<SafetyCertificateOutlined/>:<DesktopOutlined/>}</span><span>Internet<span className="brand-accent">Cafe</span><small>{isAdmin?'HỆ THỐNG':isStaff?'CỔNG NHÂN VIÊN':'MANAGEMENT STUDIO'}</small></span></Link><div className="workspace-badge"><span className="location-dot"/> {isAdmin?'Quản trị truy cập':isStaff?'Ca làm của bạn':'Cơ sở chính'}<Tag bordered={false}>DEMO</Tag></div><Menu mode="inline" selectedKeys={[location.pathname]} items={items} onClick={({key})=>{navigate(key);setMobile(false);}} className="side-menu"/><div className="sidebar-bottom"><div><span className="online-dot"/> Môi trường {apiMode==='mock'?'MSW':'HTTP'}</div><small>{apiMode==='mock'?'Dữ liệu riêng trong tab trình duyệt':'Dùng chung API được cấu hình'}</small></div></>;
  return <Layout className={`app-shell ${isAdmin?'system-shell':isStaff?'staff-shell':''}`}><Layout.Sider width={246} className="desktop-sidebar">{nav}</Layout.Sider><Drawer title="Điều hướng" placement="left" width={290} open={mobile} onClose={()=>setMobile(false)} styles={{body:{padding:0}}}>{nav}</Drawer><Layout className="main-layout"><header className="topbar"><div className="topbar-context"><Button className="mobile-menu" aria-label="Mở điều hướng" icon={<MenuOutlined/>} onClick={()=>setMobile(true)}/><span className="topbar-label">{isAdmin?'Hệ thống':isStaff?'Cổng nhân viên':'Quản lý vận hành'}</span><span className="topbar-divider"/><span className="today-label">{new Date().toLocaleDateString('vi-VN',{weekday:'long',day:'numeric',month:'long'})}</span></div><Space><Tooltip title="Tải lại snapshot từ API. Chế độ mock đồng bộ mỗi 5 giây."><Button aria-label="Đồng bộ dữ liệu" icon={<ReloadOutlined spin={query.isFetching}/>} onClick={()=>void refresh()}/></Tooltip><Dropdown menu={{items:[{key:'role',label:roleLabel[role],disabled:true},{key:'logout',icon:<LogoutOutlined/>,label:'Đăng xuất',onClick:logout}]}}><Button type="text" className="account-button"><Avatar size={30} style={{background:'#dcece7',color:'#14594f'}}>{session.user.fullName.slice(0,1)}</Avatar><span>{session.user.fullName}<small>{roleLabel[role]}</small></span></Button></Dropdown></Space></header><main className="main-content"><div className="connection-line"><Badge status={!online||query.isError?'error':'success'}/><span>{!online?'Mất kết nối mạng':query.isError?'Đồng bộ thất bại — dữ liệu có thể cũ':query.isFetching?'Đang đồng bộ…':`Đã đồng bộ ${query.dataUpdatedAt?new Date(query.dataUpdatedAt).toLocaleTimeString('vi-VN'):'—'}`}</span><Tag bordered={false}>DỮ LIỆU MÔ PHỎNG</Tag></div>{query.isError&&<div className="section-alert"><ErrorState error={query.error} retry={()=>void refresh()}/></div>}{query.isPending?<div className="page-loading"><Spin size="large"/><p>Đang chuẩn bị không gian làm việc…</p></div>:query.data?<Outlet context={{session,workspace:query.data,refresh,loading:query.isFetching}}/>:null}</main><footer className="app-footer">InternetCafe <span>Frontend demo · Backend và khóa Windows chưa tích hợp</span></footer></Layout></Layout>;
}
function Guard({session,roles,children}:{session:Session;roles:Role[];children:React.ReactNode}){return roles.includes(session.user.role)?children:<Result status="403" title="403" subTitle="Bạn không có quyền truy cập khu vực này." extra={<Link to={homeFor(session.user.role)}><Button type="primary">Về không gian của tôi</Button></Link>}/>;}
function PermissionMatrix(){return <><div className="page-title"><div><div className="eyebrow">QUẢN TRỊ HỆ THỐNG</div><h1>Ma trận quyền</h1><p>Quyền được kiểm tra tại API; việc ẩn nút trên web chỉ giúp điều hướng đúng.</p></div></div><div className="permission-grid">{([['Admin','Tài khoản và vai trò. Tra cứu sản phẩm, nhà cung cấp. Không xử lý tiền hay vận hành.'],['Owner','Toàn bộ quản lý vận hành, nhân sự và báo cáo.'],['Manager','Phòng máy, F&B, kho, CRM, nhân sự và báo cáo.'],['Cashier','Phòng máy, nạp tiền, đơn hàng; đọc khách hàng và thực đơn.'],['Staff','Chỉ hồ sơ, lịch làm, chấm công, nghỉ phép và lương của mình.'],['Customer','Desktop: hồ sơ, phiên chơi, ví, đặt món, phản hồi và khảo sát của mình.']] as [Role,string][]).map(([role,description])=><Card key={role} title={<Space><SafetyCertificateOutlined/>{roleLabel[role]}</Space>}><Tag>{role}</Tag><p>{description}</p></Card>)}</div></>;}
export function App(){
  const [session,setSession]=useState(readSession);useEffect(()=>{const listener=()=>setSession(readSession());window.addEventListener('session-changed',listener);return()=>window.removeEventListener('session-changed',listener);},[]);
  return <Routes><Route path="/login" element={<Login session={session}/>}/>{session?<Route element={<Shell session={session}/>}><Route index element={<Navigate replace to={homeFor(session.user.role)}/>}/><Route path="/management/overview" element={<Guard session={session} roles={['Owner','Manager','Cashier']}><DashboardPage/></Guard>}/><Route path="/management/computers" element={<Guard session={session} roles={['Owner','Manager','Cashier']}><MachinesPage/></Guard>}/>{modules.filter(m=>m.key!=='accounts').map(m=><Route key={m.key} path={`/management/${m.key}`} element={<Guard session={session} roles={m.roles}><ResourcePage key={m.key} module={m}/></Guard>}/>)}<Route path="/management/reports" element={<Guard session={session} roles={['Owner','Manager']}><ReportsPage/></Guard>}/><Route path="/system/accounts" element={<Guard session={session} roles={['Admin']}><ResourcePage module={modules.find(m=>m.key==='accounts')!}/></Guard>}/><Route path="/system/permissions" element={<Guard session={session} roles={['Admin']}><PermissionMatrix/></Guard>}/>{['products','suppliers'].map(key=><Route key={key} path={`/system/${key}`} element={<Guard session={session} roles={['Admin']}><ResourcePage key={key} readonly module={modules.find(m=>m.key===key)!}/></Guard>}/>)}<Route path="/staff/home" element={<Guard session={session} roles={['Staff']}><StaffPage/></Guard>}/><Route path="*" element={<Result status="404" title="Không tìm thấy trang" extra={<Link to={homeFor(session.user.role)}>Về trang chính</Link>}/>}/></Route>:<Route path="*" element={<Navigate replace to="/login"/>}/>}</Routes>;
}
