import type { Role } from './domain';
export type FieldType = 'text' | 'textarea' | 'number' | 'money' | 'select' | 'boolean' | 'date' | 'time' | 'month' | 'password' | 'email';
export interface Field { key: string; label: string; type?: FieldType; required?: boolean; options?: string[]; resource?: string; min?: number; max?: number; createOnly?: boolean; help?: string }
export interface Module { key: string; title: string; singular: string; description: string; section: string; roles: Role[]; editRoles?: Role[]; fields: Field[]; columns: string[]; statuses?: string[]; create?: boolean; edit?: boolean; remove?: boolean; dates?: boolean }
const mgr: Role[] = ['Owner', 'Manager'];
const ops: Role[] = [...mgr, 'Cashier'];
const f = (key: string, label: string, type: FieldType = 'text', options: Partial<Field> = {}): Field => ({ key, label, type, ...options });
export const modules: Module[] = [
  { key: 'customers', title: 'Khách hàng', singular: 'khách hàng', description: 'Hồ sơ, hạng thành viên và lịch sử sử dụng dịch vụ.', section: 'Khách hàng & CRM', roles: ops, editRoles: mgr, create: true, edit: true, remove: true, statuses: ['Active','Banned','Inactive'], columns: ['fullName','username','phone','tier','balance','status'], fields: [f('fullName','Họ tên','text',{required:true}),f('username','Tên đăng nhập','text',{required:true,createOnly:true}),f('password','Mật khẩu ban đầu','password',{required:true,createOnly:true}),f('phone','Điện thoại','text',{required:true}),f('email','Email','email'),f('dateOfBirth','Ngày sinh','date',{required:true}),f('hobbies','Sở thích','text',{help:'Ví dụ: FPS, MOBA, âm nhạc'}),f('tier','Hạng thành viên','select',{options:['Silver','Gold','Diamond'],required:true})] },
  { key: 'topups', title: 'Yêu cầu nạp tiền', singular: 'yêu cầu', description: 'Xác nhận sau khi đã nhận tiền tại quầy. Mỗi yêu cầu chỉ được xử lý một lần.', section: 'Vận hành', roles: ops, columns: ['customerId','amount','note','status','createdAt'], statuses:['Pending','Approved','Rejected'], dates:true, fields: [] },
  { key: 'transactions', title: 'Sổ giao dịch', singular: 'giao dịch', description: 'Tiền nạp, tiêu dùng và hoàn tiền được ghi nhận riêng biệt.', section: 'Vận hành', roles: ops, columns: ['customerId','type','amount','referenceId','createdAt'], dates:true, fields: [] },
  { key: 'sessions', title: 'Lịch sử phiên chơi', singular: 'phiên chơi', description: 'Đối chiếu thời gian và số tiền do service tính toán.', section: 'Vận hành', roles: ops, columns: ['customerId','computerId','startTime','endTime','amount','status'], statuses:['Active','Completed'], dates:true, fields: [] },
  { key: 'orders', title: 'Đơn dịch vụ', singular: 'đơn hàng', description: 'Tiếp nhận, chuẩn bị và phục vụ đơn F&B theo từng máy.', section: 'Vận hành', roles: ops, columns: ['computerId','customerId','total','note','status','createdAt'], statuses:['Pending','Preparing','Served','Cancelled'], dates:true, fields: [] },
  { key: 'products', title: 'Thực đơn', singular: 'món', description: 'Danh mục món, hình ảnh, giá bán và tình trạng phục vụ.', section: 'Thực đơn & kho', roles: ops, editRoles:mgr, create:true,edit:true,remove:true, columns:['name','categoryId','price','stock','active'], fields:[f('name','Tên món','text',{required:true}),f('categoryId','Danh mục','select',{resource:'categories',required:true}),f('price','Giá bán','money',{required:true,min:0}),f('imageUrl','URL ảnh','text',{help:'Đường dẫn HTTPS hoặc /images/...; bỏ trống để dùng hình mặc định.'}),f('active','Đang bán','boolean')] },
  { key: 'categories', title: 'Danh mục món', singular: 'danh mục', description: 'Sắp xếp thực đơn để khách tìm món nhanh hơn.', section: 'Thực đơn & kho', roles:mgr,create:true,edit:true,remove:true,columns:['name'],fields:[f('name','Tên danh mục','text',{required:true})] },
  { key: 'suppliers', title: 'Nhà cung cấp', singular: 'nhà cung cấp', description: 'Thông tin đối tác và liên hệ cung ứng hàng hóa.', section: 'Thực đơn & kho',roles:mgr,create:true,edit:true,remove:true,columns:['name','phone','email','address','active'],fields:[f('name','Tên nhà cung cấp','text',{required:true}),f('phone','Điện thoại','text',{required:true}),f('email','Email','email'),f('address','Địa chỉ'),f('active','Hoạt động','boolean')] },
  { key: 'inventory', title: 'Nhập · xuất kho', singular: 'phiếu kho', description: 'Biến động hàng hóa và cảnh báo tồn kho. Mỗi phiếu cập nhật tồn qua API.',section:'Thực đơn & kho',roles:mgr,create:true,columns:['productId','supplierId','type','quantity','note','createdAt'],dates:true,fields:[f('productId','Sản phẩm','select',{resource:'products',required:true}),f('supplierId','Nhà cung cấp','select',{resource:'suppliers'}),f('type','Loại phiếu','select',{options:['Import','Export'],required:true}),f('quantity','Số lượng','number',{required:true,min:1,max:100000}),f('note','Ghi chú','textarea',{required:true})] },
  { key:'feedback',title:'Phản hồi & hỗ trợ',singular:'phản hồi',description:'Tiếp nhận yêu cầu, phản hồi sản phẩm và theo dõi kết quả xử lý.',section:'Khách hàng & CRM',roles:mgr,edit:true,statuses:['Pending','Processing','Resolved'],columns:['customerId','subject','content','status','createdAt'],dates:true,fields:[f('status','Trạng thái','select',{options:['Pending','Processing','Resolved'],required:true}),f('response','Phản hồi cho khách','textarea',{required:true})] },
  { key:'surveys',title:'Khảo sát khách hàng',singular:'khảo sát',description:'Soạn câu hỏi, chọn tài khoản nhận và theo dõi từng câu trả lời.',section:'Khách hàng & CRM',roles:mgr,create:true,edit:true,columns:['title','status','customerIds','responses'],statuses:['Draft','Published','Closed'],fields:[f('title','Tiêu đề','text',{required:true}),f('description','Mô tả','textarea')] },
  { key:'employees',title:'Hồ sơ nhân sự',singular:'nhân viên',description:'Thông tin, bộ phận, trình độ và tình trạng làm việc.',section:'Nhân sự',roles:mgr,create:true,edit:true,remove:true,statuses:['Active','Inactive'],columns:['fullName','department','position','qualification','baseSalary','status'],fields:[f('fullName','Họ tên','text',{required:true}),f('phone','Điện thoại','text',{required:true}),f('email','Email','email'),f('department','Bộ phận','text',{required:true}),f('position','Chức vụ','text',{required:true}),f('qualification','Trình độ','text',{required:true}),f('baseSalary','Lương cơ bản','money',{required:true,min:0}),f('joinedAt','Ngày vào làm','date',{required:true}),f('status','Trạng thái','select',{options:['Active','Inactive'],required:true})] },
  { key:'shifts',title:'Ca làm việc',singular:'ca',description:'Thiết lập khung giờ ca cho lịch làm việc.',section:'Nhân sự',roles:mgr,create:true,edit:true,remove:true,columns:['name','startTime','endTime'],fields:[f('name','Tên ca','text',{required:true}),f('startTime','Giờ bắt đầu','time',{required:true}),f('endTime','Giờ kết thúc','time',{required:true})] },
  { key:'schedules',title:'Phân lịch làm',singular:'lịch làm',description:'Phân công nhân viên theo ngày và ca.',section:'Nhân sự',roles:mgr,create:true,edit:true,remove:true,statuses:['Scheduled','Completed','Absent','OnLeave'],columns:['employeeId','date','shiftId','status'],fields:[f('employeeId','Nhân viên','select',{resource:'employees',required:true}),f('shiftId','Ca làm','select',{resource:'shifts',required:true}),f('date','Ngày làm','date',{required:true}),f('status','Trạng thái','select',{options:['Scheduled','Completed','Absent','OnLeave'],required:true})] },
  { key:'leaves',title:'Duyệt đơn nghỉ',singular:'đơn nghỉ',description:'Duyệt nghỉ phép, nghỉ ốm hoặc nguyện vọng nghỉ việc.',section:'Nhân sự',roles:mgr,columns:['employeeId','type','startDate','endDate','reason','status'],statuses:['Pending','Approved','Rejected'],fields:[] },
  { key:'attendance',title:'Bảng chấm công',singular:'chấm công',description:'Theo dõi giờ vào và giờ ra theo lịch phân công.',section:'Nhân sự',roles:mgr,columns:['employeeId','scheduleId','checkIn','checkOut'],dates:true,fields:[] },
  { key:'payroll',title:'Bảng lương',singular:'phiếu lương',description:'Lương cơ bản + thưởng − khấu trừ; tổng tiền do service tính.',section:'Nhân sự',roles:mgr,create:true,edit:true,columns:['employeeId','month','baseSalary','bonus','deduction','total','status'],statuses:['Draft','Approved','Paid'],fields:[f('employeeId','Nhân viên','select',{resource:'employees',required:true}),f('month','Tháng','month',{required:true}),f('baseSalary','Lương cơ bản','money',{required:true,min:0}),f('bonus','Thưởng','money',{min:0}),f('deduction','Khấu trừ','money',{min:0}),f('status','Trạng thái','select',{options:['Draft','Approved','Paid'],required:true})] },
  { key:'accounts',title:'Tài khoản & phân quyền',singular:'tài khoản',description:'Quản lý quyền truy cập; tách biệt với nghiệp vụ vận hành quán.',section:'Quản trị hệ thống',roles:['Admin'],create:true,edit:true,remove:true,columns:['username','fullName','role','status','employeeId'],statuses:['Active','Banned'],fields:[f('username','Tên đăng nhập','text',{required:true,createOnly:true}),f('password','Mật khẩu ban đầu','password',{required:true,createOnly:true}),f('fullName','Họ tên','text',{required:true}),f('role','Vai trò','select',{options:['Admin','Owner','Manager','Cashier','Staff'],required:true}),f('employeeId','Mã nhân viên','text',{help:'Bắt buộc với Staff; phải là mã hồ sơ nhân sự đã có.'}),f('status','Trạng thái','select',{options:['Active','Banned'],required:true})] },
];
export const columnLabels: Record<string,string> = { id:'Mã',name:'Tên',fullName:'Họ tên',username:'Tên đăng nhập',phone:'Điện thoại',tier:'Hạng',balance:'Số dư',status:'Trạng thái',customerId:'Khách hàng',computerId:'Máy',amount:'Số tiền',note:'Ghi chú',createdAt:'Thời gian',referenceId:'Tham chiếu',type:'Loại',total:'Tổng tiền',categoryId:'Danh mục',price:'Giá bán',stock:'Tồn kho',active:'Hoạt động',email:'Email',address:'Địa chỉ',productId:'Sản phẩm',supplierId:'Nhà cung cấp',quantity:'Số lượng',subject:'Chủ đề',content:'Nội dung',title:'Tên khảo sát',customerIds:'Người nhận',responses:'Phản hồi',department:'Bộ phận',position:'Chức vụ',qualification:'Trình độ',baseSalary:'Lương cơ bản',employeeId:'Nhân viên',date:'Ngày',shiftId:'Ca',startTime:'Bắt đầu',endTime:'Kết thúc',startDate:'Từ ngày',endDate:'Đến ngày',reason:'Lý do',checkIn:'Giờ vào',checkOut:'Giờ ra',scheduleId:'Lịch làm',month:'Tháng',bonus:'Thưởng',deduction:'Khấu trừ',role:'Vai trò',hourlyRate:'Giá giờ',zone:'Khu vực',online:'Kết nối',response:'Trả lời',hobbies:'Sở thích',dateOfBirth:'Ngày sinh',joinedAt:'Ngày vào làm',items:'Chi tiết món',questions:'Câu hỏi',startBalance:'Số dư đầu phiên',imageUrl:'Ảnh' };
