<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>WinExe</OutputType><TargetFramework>net10.0-windows</TargetFramework><UseWPF>true</UseWPF><AssemblyName>InternetCafe.Client</AssemblyName></PropertyGroup><ItemGroup><ProjectReference Include="../InternetCafe.Client.Core/InternetCafe.Client.Core.csproj"/><PackageReference Include="MaterialDesignThemes" Version="5.3.0"/><PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.0"/></ItemGroup><ItemGroup><None Update="appsettings.json" CopyToOutputDirectory="PreserveNewest"/></ItemGroup></Project>
